const BOOK={page:36,visible:36,side:'sell',data:null,sources:{hodlhodl:['Hodl Hodl','hodl',1],peach:['Peach','peach',1],robosats:['RoboSats','robo'],mostro:['Mostro','mostro'],lnp2pbot:['LNP2PBot','lnp'],bisq:['Bisq','bisq']}};
const $=id=>document.getElementById(id),ui={currency:$('currencyFilter'),source:$('sourceFilter'),payment:$('paymentMethodFilter'),amount:$('amountFilter'),sort:$('sortFilter'),offers:$('offersContainer'),loading:$('loading'),error:$('error'),more:$('loadMoreBtn'),refresh:$('refreshBtn'),time:$('snapshotTime'),health:$('sourceHealth')};

document.addEventListener('DOMContentLoaded',()=>{document.querySelectorAll('[data-side]').forEach(button=>button.addEventListener('click',()=>{BOOK.side=button.dataset.side;BOOK.visible=BOOK.page;document.querySelectorAll('[data-side]').forEach(item=>item.classList.toggle('active',item===button));render()}));[ui.currency,ui.source,ui.payment,ui.sort].forEach(control=>control.addEventListener('change',reset));ui.amount.addEventListener('input',reset);ui.refresh.addEventListener('click',()=>load(true));ui.more.addEventListener('click',()=>{BOOK.visible+=BOOK.page;render()});load();loadPrice()});
function reset(){BOOK.visible=BOOK.page;render()}

async function load(force=false){ui.loading.hidden=false;ui.error.hidden=true;ui.refresh.classList.toggle('spinning',force);const api='https://api.github.com/repos/StellarStoic/satoshi/contents/offers-data.json?ref=p2p-data',cdn='https://cdn.jsdelivr.net/gh/StellarStoic/satoshi@p2p-data/offers-data.json',raw='https://raw.githubusercontent.com/StellarStoic/satoshi/p2p-data/offers-data.json',local='offers-data.json',remote=[api,cdn,raw],sources=['localhost','127.0.0.1'].includes(location.hostname)?[local,...remote]:[...remote,local];let failed=true;for(const source of sources){try{BOOK.data=prepare(await fetchSnapshot(source));filters();health();render();ui.time.textContent=`Updated ${ago(BOOK.data.generated_at)}`;failed=false;break}catch(error){console.warn('Order book source failed',source,error)}}ui.loading.hidden=true;ui.refresh.classList.remove('spinning');if(failed){ui.error.textContent='The public order-book snapshot is temporarily unavailable.';ui.error.hidden=false}}
async function fetchSnapshot(source){const response=await fetch(`${source}${source.includes('?')?'&':'?'}v=${Date.now()}`,{cache:'no-store',headers:{Accept:'application/vnd.github+json, application/json'}});if(!response.ok)throw Error(`HTTP ${response.status}`);const payload=await response.json();if(source.includes('api.github.com')){if(!payload.content)throw Error('GitHub returned no snapshot content');const bytes=Uint8Array.from(atob(payload.content.replace(/\s/g,'')),character=>character.charCodeAt(0));return JSON.parse(new TextDecoder().decode(bytes))}return payload}
function prepare(snapshot){if(snapshot.schema===2)return snapshot;const offers=(snapshot.offers||[]).map(raw=>{const methods=raw.payment_method_instructions||raw.payment_methods||[],trader=raw.trader||{};return{id:raw.id,source:'hodlhodl',side:raw.side,currency:raw.currency_code,price:num(raw.price),fiat_min:num(raw.min_amount),fiat_max:num(raw.max_amount),sats_min:num(raw.min_amount_sats),sats_max:num(raw.max_amount_sats),premium:num(raw.exchange_price_deviation),payment_methods:methods.map(method=>method.payment_method_name||method.name).filter(Boolean),country:raw.country,trader:trader.login,trades:num(trader.trades_count),rating:num(trader.rating),online:trader.online_status==='online',layer:raw.asset_layer||'onchain',url:`https://hodlhodl.com/offers/${encodeURIComponent(raw.id)}`}});return{...snapshot,schema:2,offers,sources:['hodlhodl'],source_status:{hodlhodl:{ok:true,count:offers.length}}}}
function filters(){const offers=BOOK.data.offers;fill(ui.currency,unique(offers.map(o=>o.currency)),'All currencies');fill(ui.source,unique(offers.map(o=>o.source)),'All markets',sourceName);fillEntries(ui.payment,paymentOptions(offers),'All methods')}
function fill(select,values,first,label=value=>value){const selected=select.value;select.replaceChildren(new Option(first,''));values.forEach(value=>select.add(new Option(label(value),value)));if(values.includes(selected))select.value=selected}
function fillEntries(select,entries,first){const selected=select.value;select.replaceChildren(new Option(first,''));entries.forEach(({key,label})=>select.add(new Option(label,key)));if(entries.some(entry=>entry.key===selected))select.value=selected}
function health(){const counts=Object.fromEntries(Object.keys(BOOK.sources).map(key=>[key,0]));BOOK.data.offers.forEach(o=>counts[o.source]=(counts[o.source]||0)+1);ui.health.innerHTML=Object.entries(BOOK.sources).map(([key,meta])=>`<button type="button" data-pick="${key}" class="source-pill ${counts[key]?'available':'quiet'}"><span></span>${esc(meta[0])}<b>${counts[key]||0}</b></button>`).join('');ui.health.querySelectorAll('[data-pick]').forEach(button=>button.addEventListener('click',()=>{ui.source.value=button.dataset.pick;reset()}))}
function matching(){const amount=num(ui.amount.value),offers=BOOK.data.offers.filter(o=>o.side===BOOK.side&&(!ui.currency.value||o.currency===ui.currency.value)&&(!ui.source.value||o.source===ui.source.value)&&(!ui.payment.value||(o.payment_methods||[]).some(method=>methodKey(method)===ui.payment.value))&&(amount===null||amount<=0||!((o.fiat_min!==null&&amount<o.fiat_min)||(o.fiat_max!==null&&amount>o.fiat_max))));const direction=BOOK.side==='sell'?1:-1;offers.sort((a,b)=>ui.sort.value==='recent'?date(b.created_at)-date(a.created_at):ui.sort.value==='premium'?nullable(a.premium,b.premium,1):nullable(a.price,b.price,direction));return offers}
function render(){if(!BOOK.data)return;const offers=matching(),visible=offers.slice(0,BOOK.visible);$('offerTotal').textContent=offers.length.toLocaleString();$('marketTotal').textContent=new Set(offers.map(o=>o.source)).size;$('currencyTotal').textContent=new Set(offers.map(o=>o.currency)).size;ui.offers.innerHTML=visible.length?visible.map(card).join(''):'<div class="empty-book"><i class="lni lni-search-2"></i><h2>No matching offers</h2><p>Change a filter or try the opposite trade direction.</p></div>';ui.more.hidden=visible.length>=offers.length;ui.more.textContent=`Show ${Math.min(BOOK.page,offers.length-visible.length)} more`}
function card(o){const source=BOOK.sources[o.source]||[o.source,'other'],allMethods=paymentOptions([{payment_methods:o.payment_methods||[]}]).map(method=>method.label),methods=allMethods.slice(0,4),extra=allMethods.length-methods.length,meta=[o.layer,o.country].filter(Boolean).map(item=>`<span>${esc(item)}</span>`).join(''),market=o.source==='mostro'&&o.price===null,reference=o.source==='peach'&&o.side==='buy'&&o.premium===null;return `<article class="offer-card source-${source[1]}"><div class="offer-topline"><span class="source-mark">${esc(source[0])}</span><span class="side-label">${o.side==='sell'?'SELLS BTC':'BUYS BTC'}</span>${o.online===true?'<span class="online-label">online</span>':''}</div><div class="offer-primary"><div><small>${market?'Market price':reference?'Market reference':'Price for 1 BTC'}</small><strong>${market?'<span class="unknown">Set when order is taken</span>':money(o.price,o.currency)}</strong></div><div class="rate-stack">${o.bond!==null&&o.bond!==undefined?`<div class="bond">${Number(o.bond).toFixed(0)}% bond</div>`:''}<div class="premium ${o.premium!==null&&o.premium<0?'discount':''}">${premium(o.premium)}</div></div></div><div class="offer-range"><div><small>Fiat limits</small><b>${range(o.fiat_min,o.fiat_max,o.currency,false)}</b></div><div><small>Bitcoin limits</small><b>${range(o.sats_min,o.sats_max,'sats',true)}</b></div></div><div class="method-row">${methods.length?methods.map(method=>`<span>${esc(method)}</span>`).join(''):'<span class="muted">Payment method on platform</span>'}${extra>0?`<span>+${extra}</span>`:''}</div><div class="offer-footer"><div class="trader-line">${meta}${o.trader?`<span>${esc(short(o.trader,18))}</span>`:''}${o.trades!==null?`<span>${Math.round(o.trades)} trades</span>`:''}${o.rating!==null?`<span>${rating(o.rating)}</span>`:''}</div>${offerActions(o)}</div></article>`}

function offerActions(o){if(o.source==='robosats')return '<a href="http://robosatsy56bwqn56qyadmcxkx767hnabg4mihxlmgyt6if5gnuxvzad.onion/offers" target="_blank" rel="noopener" title="Requires Tor Browser">Open in Tor <i class="lni lni-arrow-up-right"></i></a>';const custom=String(o.url||'').startsWith('mostro:'),affiliate=BOOK.sources[o.source]?.[2]?' sponsored':'';return `<a href="${url(o.url)}"${custom?'':' target="_blank"'} rel="noopener${affiliate}">${custom?'Open in app':'Open offer'} <i class="lni lni-arrow-up-right"></i></a>`}

async function loadPrice(){const cached=cachedPrice();if(cached)showPrice(cached);try{const value=await sintra();if(value)showPrice(value)}catch{}}
function sintra(){return new Promise((resolve,reject)=>{const socket=new WebSocket('wss://api.sintra.fi/ws'),timer=setTimeout(()=>{socket.close();reject(Error('timeout'))},5000);socket.onmessage=event=>{try{const price=num(JSON.parse(event.data)?.data?.prices?.usd);if(price){clearTimeout(timer);socket.close();resolve(price)}}catch{}};socket.onerror=reject})}
function cachedPrice(){try{const rates=JSON.parse(localStorage.getItem('exchangeRatesCache'));return num(rates?.BTC)?1/rates.BTC:null}catch{return null}}
function showPrice(price){$('currentPrice').innerHTML=`<span>${compact(price,'USD')}</span><small>BTC / USD</small>`}
function sourceName(key){return BOOK.sources[key]?.[0]||key}function unique(values){return[...new Set(values.filter(Boolean))].sort((a,b)=>a.localeCompare(b))}function num(value){const parsed=Number(value);return value!==''&&value!==null&&Number.isFinite(parsed)?parsed:null}function date(value){const parsed=Date.parse(value);return Number.isFinite(parsed)?parsed:0}function nullable(a,b,direction){if(a===null)return 1;if(b===null)return-1;return(a-b)*direction}function short(value,length){return value.length>length?`${value.slice(0,length-1)}...`:value}
const METHOD_LABELS={paypal:'PayPal',revolut:'Revolut',wise:'Wise',sepa:'SEPA',zelle:'Zelle',venmo:'Venmo',strike:'Strike',cashapp:'Cash App',interac:'Interac',bizum:'Bizum',skrill:'Skrill',neteller:'Neteller'};
function methodText(value){if(value&&typeof value==='object')return value.name||value.payment_method_name||value.type||'';return String(value||'')}
function methodKey(value){return methodText(value).normalize('NFKD').toLocaleLowerCase().replace(/[\p{P}\p{S}\s]+/gu,'')}
function methodLabel(value){const text=methodText(value).normalize('NFKC').trim().replace(/\s+/g,' '),key=methodKey(text);if(METHOD_LABELS[key])return METHOD_LABELS[key];if(!text)return'';return text===text.toLocaleLowerCase()?text.replace(/\b\p{L}/gu,char=>char.toLocaleUpperCase()):text}
function paymentOptions(offers){const methods=new Map;offers.flatMap(offer=>offer.payment_methods||[]).forEach(method=>{const key=methodKey(method);if(key&&!methods.has(key))methods.set(key,methodLabel(method))});return[...methods].map(([key,label])=>({key,label})).sort((a,b)=>a.label.localeCompare(b.label))}
function url(value){try{const parsed=new URL(value);return['http:','https:','mostro:'].includes(parsed.protocol)?esc(parsed.href):'#'}catch{return'#'}}function esc(value){const node=document.createElement('span');node.textContent=String(value??'');return node.innerHTML}function premium(value){return value===null?'<span>premium n/a</span>':`${value>0?'+':''}${value.toFixed(2)}% premium`}function rating(value){return value<=1?`${Math.round(value*100)}% rating`:`${value.toFixed(1)} rating`}function money(value,currency){return value===null?'<span class="unknown">Price on platform</span>':compact(value,currency)}
function compact(value,currency){try{return new Intl.NumberFormat(undefined,{style:'currency',currency,maximumFractionDigits:value>=1000?0:2}).format(value)}catch{return`${value.toLocaleString()} ${currency}`}}function range(min,max,unit,sats){if(min===null&&max===null)return'Not published';const format=value=>sats?`${Math.round(value).toLocaleString()} sats`:compact(value,unit);if(min===null)return`Up to ${format(max)}`;if(max===null)return`From ${format(min)}`;return min===max?format(min):`${format(min)} - ${format(max)}`}
function ago(value){const seconds=Math.max(0,Math.round((Date.now()-Date.parse(value))/1000));if(seconds<60)return'just now';if(seconds<3600)return`${Math.round(seconds/60)}m ago`;if(seconds<86400)return`${Math.round(seconds/3600)}h ago`;return`${Math.round(seconds/86400)}d ago`}
